# Generated by Django 3.2.25 on 2026-02-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allergic_to_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='can_lie_still',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_sensitivities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='understands_risks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='wears_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='refillprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
