# Generated by Django 3.2.25 on 2026-02-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20260215_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
